// DAY 9 - ARRAY MANIPULATION
import java.util.*;
class Problem1{public static void main(String[]a){Scanner s=new Scanner(System.in);int n=s.nextInt();int[]x=new int[n];for(int i=0;i<n;i++)x[i]=s.nextInt();for(int i=0;i<n;i++)for(int j=i+1;j<n;j++)if(x[i]==x[j]){System.out.print(x[i]+" ");break;}}}
class Problem2{public static void main(String[]a){Scanner s=new Scanner(System.in);int n=s.nextInt(),m=Integer.MIN_VALUE,sec=Integer.MIN_VALUE;for(int i=0;i<n;i++){int x=s.nextInt();if(x>m){sec=m;m=x;}else if(x>sec&&x!=m)sec=x;}System.out.print(sec);}}
class Problem3{public static void main(String[]a){Scanner s=new Scanner(System.in);int n=s.nextInt(),sum=0;for(int i=1;i<=n;i++)sum^=i;for(int i=0;i<n-1;i++)sum^=s.nextInt();System.out.print(sum);}}
class Problem4{public static void main(String[]a){Scanner s=new Scanner(System.in);int n=s.nextInt(),k=s.nextInt();int[]x=new int[n];for(int i=0;i<n;i++)x[i]=s.nextInt();k%=n;for(int q=0;q<k;q++){int t=x[n-1];for(int i=n-1;i>0;i--)x[i]=x[i-1];x[0]=t;}System.out.println(Arrays.toString(x));}}
class Problem5{public static void main(String[]a){Scanner s=new Scanner(System.in);int n=s.nextInt(),k=s.nextInt();int[]x=new int[n];for(int i=0;i<n;i++)x[i]=s.nextInt();for(int q=0;q<k%n;q++){int t=x[0];for(int i=0;i<n-1;i++)x[i]=x[i+1];x[n-1]=t;}System.out.println(Arrays.toString(x));}}
class Problem6{public static void main(String[]a){Scanner s=new Scanner(System.in);int n=s.nextInt();int[]x=new int[n];for(int i=0;i<n;i++)x[i]=s.nextInt();int p=0;for(int v:x)if(v!=0)x[p++]=v;while(p<n)x[p++]=0;System.out.println(Arrays.toString(x));}}
class Problem7{public static void main(String[]a){Scanner s=new Scanner(System.in);int n=s.nextInt(),k=s.nextInt();int[]x=new int[n];for(int i=0;i<n;i++)x[i]=s.nextInt();boolean ok=false;for(int i=0;i<n;i++)for(int j=i+1;j<n;j++)if(x[i]+x[j]==k)ok=true;System.out.print(ok);}}
class Problem8{public static void main(String[]a){Scanner s=new Scanner(System.in);int n=s.nextInt();int[]x=new int[n];for(int i=0;i<n;i++)x[i]=s.nextInt();for(int v:x){int c=0;for(int y:x)if(v==y)c++;if(c==1)System.out.print(v+" ");}}}
class Problem9{public static void main(String[]a){Scanner s=new Scanner(System.in);int n=s.nextInt();int[]x=new int[n];for(int i=0;i<n;i++)x[i]=s.nextInt();int best=x[0],bc=0;for(int v:x){int c=0;for(int y:x)if(v==y)c++;if(c>bc){bc=c;best=v;}}System.out.print(best);}}
class Problem10{public static void main(String[]a){Scanner s=new Scanner(System.in);int n=s.nextInt();int[]x=new int[n];for(int i=0;i<n;i++)x[i]=s.nextInt();for(int i=0;i<n;i++){int sum=0;for(int j=0;j<=i;j++)sum+=x[j];System.out.print(sum+" ");}}}
