// DAY 17 - LINKED LIST ADVANCED
class Problem1{static class N{int d;N n;N(int d){this.d=d;}}public static void main(String[]x){N h=new N(1);h.n=new N(2);h.n.n=new N(3);for(N p=h;p!=null;p=p.n)System.out.print(p.d+" ");}}
class Problem2{static class N{int d;N n;N(int d){this.d=d;}}public static void main(String[]x){N h=new N(1);h.n=new N(2);h.n.n=new N(3);N s=h,f=h;while(f!=null&&f.n!=null){s=s.n;f=f.n.n;}System.out.print(s.d);}}
class Problem3{static class N{int d;N n;N(int d){this.d=d;}}public static void main(String[]x){N h=new N(1);h.n=new N(2);h.n.n=new N(3);int k=2;N p=h;for(int i=1;i<k;i++)p=p.n;System.out.print(p.d);}}
class Problem4{static class N{int d;N n;N(int d){this.d=d;}}public static void main(String[]x){N h=new N(1);h.n=new N(2);h.n.n=new N(3);int n=2;N a=h,b=h;for(int i=0;i<n;i++)b=b.n;while(b!=null){a=a.n;b=b.n;}System.out.print(a.d);}}
class Problem5{static class N{int d;N n;N(int d){this.d=d;}}public static void main(String[]x){N h=new N(1);h.n=new N(2);h.n.n=new N(1);java.util.ArrayList<Integer>a=new java.util.ArrayList<>();for(N p=h;p!=null;p=p.n)a.add(p.d);boolean ok=true;for(int i=0,j=a.size()-1;i<j;i++,j--)if(!a.get(i).equals(a.get(j)))ok=false;System.out.print(ok);}}
class Problem6{static class N{int d;N n;N(int d){this.d=d;}}public static void main(String[]x){N h=new N(1);h.n=new N(2);h.n.n=new N(3);h.n.n.n=h;N s=h,f=h;do{s=s.n;f=f.n.n;}while(s!=f);System.out.print(true);}}
class Problem7{static class N{int d;N n;N(int d){this.d=d;}}public static void main(String[]x){N h=new N(1);h.n=new N(2);h.n.n=new N(3);N p=null;while(h!=null){N q=h.n;h.n=p;p=h;h=q;}for(N z=p;z!=null;z=z.n)System.out.print(z.d+" ");}}
class Problem8{static class N{int d;N n;N(int d){this.d=d;}}public static void main(String[]x){N a=new N(1);a.n=new N(3);N b=new N(2);b.n=new N(4);N h=null,t=null;while(a!=null&&b!=null){N q;if(a.d<b.d){q=a;a=a.n;}else{q=b;b=b.n;}if(h==null)h=q;else t.n=q;t=q;}if(a!=null)t.n=a;if(b!=null)t.n=b;for(N p=h;p!=null;p=p.n)System.out.print(p.d+" ");}}
class Problem9{static class N{int d;N n;N(int d){this.d=d;}}public static void main(String[]x){N h=new N(1);h.n=new N(2);h.n.n=new N(3);N p=h;while(p.n!=null)p=p.n;System.out.print(p.d);}}
class Problem10{static class N{int d;N n;N(int d){this.d=d;}}public static void main(String[]x){N h=new N(1);h.n=new N(2);h.n.n=new N(3);int sum=0;for(N p=h;p!=null;p=p.n)sum+=p.d;System.out.print(sum);}}
