// DAY 11 - SEARCHING AND SORTING
import java.util.*;
class Problem1{public static void main(String[]a){Scanner s=new Scanner(System.in);int n=s.nextInt(),k=s.nextInt(),ans=-1;for(int i=0;i<n;i++)if(s.nextInt()==k&&ans<0)ans=i;System.out.print(ans);}}
class Problem2{public static void main(String[]a){Scanner s=new Scanner(System.in);int n=s.nextInt(),k=s.nextInt();int[]x=new int[n];for(int i=0;i<n;i++)x[i]=s.nextInt();int l=0,r=n-1,ans=-1;while(l<=r){int m=(l+r)/2;if(x[m]==k){ans=m;break;}if(x[m]<k)l=m+1;else r=m-1;}System.out.print(ans);}}
class Problem3{public static void main(String[]a){Scanner s=new Scanner(System.in);int n=s.nextInt();int[]x=new int[n];for(int i=0;i<n;i++)x[i]=s.nextInt();for(int i=0;i<n-1;i++)for(int j=0;j<n-1-i;j++)if(x[j]>x[j+1]){int t=x[j];x[j]=x[j+1];x[j+1]=t;}System.out.println(Arrays.toString(x));}}
class Problem4{public static void main(String[]a){Scanner s=new Scanner(System.in);int n=s.nextInt();int[]x=new int[n];for(int i=0;i<n;i++)x[i]=s.nextInt();for(int i=0;i<n-1;i++){int p=i;for(int j=i+1;j<n;j++)if(x[j]<x[p])p=j;int t=x[i];x[i]=x[p];x[p]=t;}System.out.println(Arrays.toString(x));}}
class Problem5{public static void main(String[]a){Scanner s=new Scanner(System.in);int n=s.nextInt();int[]x=new int[n];for(int i=0;i<n;i++)x[i]=s.nextInt();for(int i=1;i<n;i++){int k=x[i],j=i-1;while(j>=0&&x[j]>k){x[j+1]=x[j];j--;}x[j+1]=k;}System.out.println(Arrays.toString(x));}}
class Problem6{public static void main(String[]a){Scanner s=new Scanner(System.in);int n=s.nextInt(),k=s.nextInt();int[]x=new int[n];for(int i=0;i<n;i++)x[i]=s.nextInt();int l=0,r=n-1,ans=-1;while(l<=r){int m=(l+r)/2;if(x[m]>=k){if(x[m]==k)ans=m;r=m-1;}else l=m+1;}System.out.print(ans);}}
class Problem7{public static void main(String[]a){Scanner s=new Scanner(System.in);int n=s.nextInt(),k=s.nextInt();int[]x=new int[n];for(int i=0;i<n;i++)x[i]=s.nextInt();int l=0,r=n-1,ans=-1;while(l<=r){int m=(l+r)/2;if(x[m]<=k){if(x[m]==k)ans=m;l=m+1;}else r=m-1;}System.out.print(ans);}}
class Problem8{public static void main(String[]a){Scanner s=new Scanner(System.in);int n=s.nextInt(),k=s.nextInt();int[]x=new int[n];for(int i=0;i<n;i++)x[i]=s.nextInt();int c=0;for(int v:x)if(v==k)c++;System.out.print(c);}}
class Problem9{public static void main(String[]a){Scanner s=new Scanner(System.in);int n=s.nextInt();int[]x=new int[n];for(int i=0;i<n;i++)x[i]=s.nextInt();boolean ok=true;for(int i=1;i<n;i++)if(x[i]<x[i-1])ok=false;System.out.print(ok);}}
class Problem10{public static void main(String[]a){Scanner s=new Scanner(System.in);int n=s.nextInt(),k=s.nextInt();int[]x=new int[n];for(int i=0;i<n;i++)x[i]=s.nextInt();Arrays.sort(x);System.out.print(Arrays.binarySearch(x,k)>=0);}}
